# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.


pipelines:
  default:
    - parallel:
      - step:
          name: 'Sync with github Repo'
          script:
            - git remote add github https://test-mendix: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@github.com/bouaouda-achraf/mendix.git
            - git push github master